### PR TITLE
Add support for extract chunks plugin

### PR DESCRIPTION
**Pull request by thisizkp**

### CODE REVIEW

**Comment by gja** [comment]
I don't think you can (should) have both ExtractCSS chunks and ExtractText plugin installed.

**Comment by thisizkp** [comment]
I added the chunk support only for the `secret-mode`; Should I do the same for entire madrid project?

**Comment by thisizkp** [comment]
~I think we can do this, but to import the chunk we need to `babel-dual-import` plugin; anyways, we need that plugin; so will add it and update the code.~

the above is needed only for dynamic-import, will remove ExtractText

**Comment by thisizkp** [comment]
closing this in favour of #4

**Pull request closed without merging**
